AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ResizeImageFunction:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.11
        Timeout: 3
        Handler: app.lambda_handler
        FunctionName: ResizeImageFunction
        CodeUri: resize_image/
        Policies:
          - Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::sp-*
                  - arn:aws:s3:::sp-*/*
        Environment:
          Variables:
            BUCKET_NAME: sp-resized-image-bucket
        Architectures:
        - x86_64

  GetPresignedUploadUrlFunction:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.11
        Timeout: 3
        Handler: app.lambda_handler
        FunctionName: GetPresignedUploadUrlFunction
        CodeUri: get_upload_url/
        Policies:
          - Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::sp-*
                  - arn:aws:s3:::sp-*/*
        Environment:
          Variables:
            BUCKET_NAME: sp-user-input-temporary-bucket
        Architectures:
        - x86_64
        Events:
          GetPresignedUploadUrl:
            Type: Api
            Properties:
              Path: /get-input-url
              Method: get

  ImageSendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Timeout: 60
      Handler: app.lambda_handler
      FunctionName: ImageSendFunction
      CodeUri: image_send/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::sp-*
                - arn:aws:s3:::sp-*/*
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
      Architectures:
      - x86_64

  ImageCompleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Timeout: 30
      Handler: app.lambda_handler
      FunctionName: ImageCompleteFunction
      CodeUri: image_complete/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - arn:aws:execute-api:*:*:*/*/@connections/*
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::sp-*/*
      Architectures:
      - x86_64
      Events:
        S3ObjectCreatedEvent:
          Type: EventBridgeRule
          Properties:
            RuleName: detect-complete-image-rule
            Pattern:
              source:
                - "aws.s3"
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - "sp-complete-bucket"

  CropFaceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Timeout: 300
      MemorySize: 2048
      Handler: app.lambda_handler
      FunctionName: CropFaceFunction
      CodeUri: crop_face/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::sp-*/*
            - Effect: Allow
              Action:
                - rekognition:DetectFaces
              Resource: "*"
      Architectures:
      - x86_64

  WebSocketConnectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Timeout: 3
      Handler: app.lambda_handler
      FunctionName: WebSocketConnectionFunction
      CodeUri: websocket_connection/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - arn:aws:execute-api:*:*:*/*/@connections/*
      Architectures:
      - x86_64
      # 여기서 연결 할 수 있으면 좋긴 한데..
      # Events:
      #   WebSocketEvent:
      #     Type: Api
      #     Properties:

  # EventBridge Rules (통합된 이벤트 규칙들)
  UserInputS3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: user-input-s3-event-rule
      Description: S3 Object Created event for sp-user-input-temporary-bucket
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - "sp-user-input-temporary-bucket"
      Targets:
        - Arn: !GetAtt ResizeImageFunction.Arn
          Id: "ResizeImageTarget"
        - Arn: !GetAtt ImageSendFunction.Arn
          Id: "ImageSendTarget"
        - Arn: !GetAtt CropFaceFunction.Arn
          Id: "CropFaceTarget"

  CompleteS3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: complete-s3-event-rule
      Description: S3 Object Created event for sp-complete-bucket
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - "sp-complete-bucket"
      Targets:
        - Arn: !GetAtt ImageCompleteFunction.Arn
          Id: "ImageCompleteTarget"

  # Lambda 권한 (EventBridge가 Lambda를 호출할 수 있도록)
  ResizeImageFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ResizeImageFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt UserInputS3EventRule.Arn

  ImageSendFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ImageSendFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt UserInputS3EventRule.Arn

  CropFaceFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CropFaceFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt UserInputS3EventRule.Arn

  ImageCompleteFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ImageCompleteFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CompleteS3EventRule.Arn

# Outputs:
  # HelloWorldApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World 
  #     function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  # HelloWorldFunction:
  #   Description: Hello World Lambda Function ARN
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: Implicit IAM Role created for Hello World function
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
