AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ResizeImageFunction:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.11
        Timeout: 3
        Handler: app.lambda_handler
        FunctionName: ResizeImageFunction
        CodeUri: resize_image/
        Policies:
          - Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::sp-*
                  - arn:aws:s3:::sp-*/*
        Environment:
          Variables:
            BUCKET_NAME: sp-resized-image-bucket
        Architectures:
        - x86_64
        Events:
          S3ObjectCreatedEvent:
            Type: EventBridgeRule
            Properties:
              RuleName: detect-user-input-rule
              Pattern:
                source:
                  - "aws.s3"
                detail-type:
                  - "Object Created"
                detail:
                  bucket:
                    name:
                      - "sp-user-input-temporary-bucket"

  GetPresignedUploadUrlFunction:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.11
        Timeout: 3
        Handler: app.lambda_handler
        FunctionName: GetPresignedUploadUrlFunction
        CodeUri: get_upload_url/
        Policies:
          - Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::sp-*
                  - arn:aws:s3:::sp-*/*
        Environment:
          Variables:
            BUCKET_NAME: sp-user-input-temporary-bucket
        Architectures:
        - x86_64
        Events:
          GetPresignedUploadUrl:
            Type: Api
            Properties:
              Path: /get-input-url
              Method: get

  WebSocketConnectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Timeout: 3
      Handler: app.lambda_handler
      FunctionName: WebSocketConnectionFunction
      CodeUri: websocket_connection/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - arn:aws:execute-api:*:*:*/*/@connections/*
      Architectures:
      - x86_64
      # 여기서 연결 할 수 있으면 좋긴 한데..
      # Events:
      #   WebSocketEvent:
      #     Type: Api
      #     Properties:

# Outputs:
  # HelloWorldApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World 
  #     function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  # HelloWorldFunction:
  #   Description: Hello World Lambda Function ARN
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: Implicit IAM Role created for Hello World function
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
